//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelBuilder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModelBuilder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ TRY ].
        /// </summary>
        internal static string _try {
            get {
                return ResourceManager.GetString("try", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ServiceModel/AuthService.svc/Login.
        /// </summary>
        internal static string authServiceUri {
            get {
                return ResourceManager.GetString("authServiceUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \creatio\clio\appsettings.json.
        /// </summary>
        internal static string clioPath {
            get {
                return ResourceManager.GetString("clioPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty entity XElement.
        /// </summary>
        internal static string EmptyXElement {
            get {
                return ResourceManager.GetString("EmptyXElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ ERROR ].
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ INFO ].
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting.
        /// </summary>
        internal static string MsgExit {
            get {
                return ResourceManager.GetString("MsgExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Not Found.
        /// </summary>
        internal static string MsgFileNotFound {
            get {
                return ResourceManager.GetString("MsgFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sit tight I am woking on it.
        /// </summary>
        internal static string MsgWait {
            get {
                return ResourceManager.GetString("MsgWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ OK ].
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully obtained connection string ....
        /// </summary>
        internal static string OkMsgGotCS {
            get {
                return ResourceManager.GetString("OkMsgGotCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Successful !!!.
        /// </summary>
        internal static string OkMsgLoginOk {
            get {
                return ResourceManager.GetString("OkMsgLoginOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Models.
        /// </summary>
        internal static string SaveToPath {
            get {
                return ResourceManager.GetString("SaveToPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Connections string from Clio settings.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to get Enity Metadata... this might take a while !.
        /// </summary>
        internal static string TryMsgAttempting {
            get {
                return ResourceManager.GetString("TryMsgAttempting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Connections string from Clio settings.
        /// </summary>
        internal static string TryMsgBuildConStr {
            get {
                return ResourceManager.GetString("TryMsgBuildConStr", resourceCulture);
            }
        }
    }
}
